name: Test and Score

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and calculate score
        run: |
          OUTPUT=$(npx jest --json --outputFile=results.json || true)
          PASSED=$(cat results.json | jq '.numPassedTests')
          TOTAL=$(cat results.json | jq '.numTotalTests')

          echo "✅ Tests Passed: $PASSED / $TOTAL"

          SCORE=$(echo "$PASSED * 0.4" | bc)
          echo "🏆 Score: $SCORE / 4"

        shell: bash

      - name: Upload test result (optional)
        uses: actions/upload-artifact@v3
        with:
          name: jest-results
          path: results.json
