name: Autograding Tests
on:
  - push
  - repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Jest and generate results.json
        run: |
          npx jest --json --outputFile=results.json

      - name: Calculate Score
        id: calculate
        run: |
          node calculate-score.js

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: calculate
        env:
          CALCULATE_RESULTS: "${{ steps.calculate.outputs.result }}"
